#Using data in file 'data/world_bank_projects.json' and the techniques demonstrated above,
#Find the 10 countries with most projects
#Find the top 10 major project themes (using column 'mjtheme_namecode')
#In 2. above you will notice that some entries have only the code and the name is missing. Create a dataframe with the missing #names filled in.

In [167]:
import pandas as pd
import json
from pandas.io.json import json_normalize
import numpy as np

#Read data into DataFrame
wbp_df = pd.read_json('data/world_bank_projects.json')
wbp_df
countries = wbp_df.loc[:'countryname','project_name']
#Find the 10 countries with most projects
top10MostProjectCountries = wbp_df.groupby(['countryname']).agg({'project_name':'count'}).nlargest(10,'project_name')

                                 project_name
countryname
People's Republic of China                 19
Republic of Indonesia                      19
Socialist Republic of Vietnam              17
Republic of India                          16
Republic of Yemen                          13
Kingdom of Morocco                         12
Nepal                                      12
People's Republic of Bangladesh            12
Africa                                     11
Republic of Mozambique                     11

In [5]:
#Find the 10 countries with most projects
import pandas as pd
import json
from pandas.io.json import json_normalize
import numpy as np

#Read data into DataFrame
wbp_df = pd.read_json('data/world_bank_projects.json')
#Get top 10 using head
top10UseHeadData = wbp_df.groupby(['countryname']).id.nunique().sort_values(ascending=False).head(10)
top10UseHeadData

countryname
People's Republic of China         19
Republic of Indonesia              19
Socialist Republic of Vietnam      17
Republic of India                  16
Republic of Yemen                  13
Nepal                              12
People's Republic of Bangladesh    12
Kingdom of Morocco                 12
Africa                             11
Republic of Mozambique             11
Name: id, dtype: int64

In [24]:
#Find the top 10 major project themes (using column 'mjtheme_namecode')
#Get data for themes
with open('data/world_bank_projects.json') as f:
    raw = json.load(f)
themes = json_normalize(raw, 'mjtheme_namecode', ['id'])
themes
themes.name.value_counts().head(10)

Environment and natural resources management    223
Rural development                               202
Human development                               197
Public sector governance                        184
Social protection and risk management           158
Financial and private sector development        130
                                                122
Social dev/gender/inclusion                     119
Trade and integration                            72
Urban development                                47
Name: name, dtype: int64

In [32]:
#Get data for themes
with open('data/world_bank_projects.json') as f:
    raw = json.load(f)
themes = json_normalize(raw, 'mjtheme_namecode', ['id'])
#Dictionary theme (name)
dic_theme = themes.name
#Create dataFrame
df = pd.DataFrame(dic_theme)
#Replace empty string with NA
df1 = df.replace('', 'NA', regex=True)
df1

                                              name
0                                Human development
1                                               NA
2                              Economic management
3            Social protection and risk management
4                            Trade and integration
5                         Public sector governance
6     Environment and natural resources management
7            Social protection and risk management
8                      Social dev/gender/inclusion
9                      Social dev/gender/inclusion
10                           Trade and integration
11        Financial and private sector development
12           Social protection and risk management
13                                              NA
14                        Public sector governance
15        Financial and private sector development
16    Environment and natural resources management
17                                              NA
18                               Rural development
19                                              NA
20                        Public sector governance
21                        Public sector governance
22                        Public sector governance
23                               Rural development
24                                              NA
25                               Rural development
26           Social protection and risk management
27           Social protection and risk management
28    Environment and natural resources management
29                                              NA
...                                            ...
1469                             Human development
1470                             Urban development
1471         Social protection and risk management
1472         Social protection and risk management
1473                             Urban development
1474                      Public sector governance
1475                      Public sector governance
1476                             Rural development
1477                                            NA
1478                             Human development
1479                   Social dev/gender/inclusion
1480  Environment and natural resources management
1481                                            NA
1482         Social protection and risk management
1483                                            NA
1484      Financial and private sector development
1485                   Social dev/gender/inclusion
1486                             Human development
1487                         Trade and integration
1488                      Public sector governance
1489                             Human development
1490                             Rural development
1491                                            NA
1492                             Rural development
1493                             Rural development
1494                             Rural development
1495                             Urban development
1496                             Human development
1497                         Trade and integration
1498      Financial and private sector development

[1499 rows x 1 columns]